# Generated by Django 3.2 on 2021-12-16 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20211215_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='superior_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinate_categories',
                                    to='categories.category'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
