# Generated by Django 3.2 on 2021-12-16 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20211216_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='superior_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinate_categories', to='categories.category'),
        ),
    ]
